# This is a basic workflow to help you get started with Actions

name: Deploy app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# workflow run
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - name: build website
      run: npm run build
    - name: Commit files
      run: |
          git config --global user.name 'Laura Hughes'
          git config --global user.email 'flaneuse@users.noreply.github.com'
          git add -A
          git commit -m 'deploy via GitHub Actions'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        directory: dist
        branch: gh-pages


